name: 'Process stale needs-feedback issues'
on:
  schedule:
    - cron: '11 0 * * *'
    - cron: '21 1 * * *'
    - cron: '31 2 * * *'
    - cron: '41 3 * * *'

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Install Actions Core
        run: npm --prefix .github/workflows/scripts install @actions/core

      - name: Get start date
        id: startdate
        run: node .github/workflows/scripts/stalebot.js
        env:
          CRON_SCHEDULE: ${{ github.event.schedule }}
      - name: Scan issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 8
          start-date: steps.startdate.outputs.stale-start-date
          stale-issue-message: "As a part of this repository's maintenance, this issue is being marked as stale due to inactivity. Please feel free to comment on it in case we missed something.\n\n###### After 7 days with no activity this issue will be automatically be closed."
          close-issue-message: 'This issue was closed because it has been 14 days with no activity.'
          days-before-issue-stale: 7
          days-before-issue-close: 7
          days-before-pr-close: -1
          stale-issue-label: 'status: stale'
          stale-pr-label: 'status: stale'
          exempt-issue-labels: 'type: enhancement'
          only-issue-labels: 'needs: author feedback'
          close-issue-label: "status: can't reproduce"
          ascending: true
